import { Poppins } from "next/font/google";
import { Providers } from "./Providers";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata = {
  title: "Bajda Arquitectos",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className="scroll-smooth bg-grey-body">
      <body className={poppins.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
